import { TTrainer } from "./types";

export const initialTrainerData: TTrainer = {
  id: "1",
  name: "Ash",
  email: "ash.ketchum@example.com",
  age: 10,
  avatar: 1,
  lineup: [
    {
      id: "#eggs",
      apiId: "5",
      ball: "01",
      name: "Cassandra",
      species: "Eggsecutor",
      type: ["Water", "Electric"],
      level: 5,
      exp: 12,
      sprite: "/placeholders/pokesprites/Eggsecutor.png",
    },
    {
      id: "#treek",
      apiId: "6",
      ball: "02",
      name: "Herbie",
      species: "Treeko",
      type: ["Water", "Electric"],
      level: 5,
      exp: 12,
      sprite: "/placeholders/pokesprites/Treeko.png",
    },
    {
      id: "#lap",
      apiId: "7",
      ball: "03",
      name: "Enoch",
      species: "Lapras",
      type: ["Water", "Electric"],
      level: 5,
      exp: 12,
      sprite: "/placeholders/pokesprites/Lapras.png",
    },
    {
      id: "#blast1",
      apiId: "9",
      ball: "04",
      name: "Michael",
      species: "Blastoise",
      type: ["Water", "Electric"],
      level: 5,
      exp: 12,
      sprite: "/placeholders/pokesprites/Blastoise.png",
    },
    {
      id: "#blast2",
      apiId: "9",
      ball: "04",
      name: "Michael",
      species: "Blastoise",
      type: ["Water", "Electric"],
      level: 5,
      exp: 12,
      sprite: "/placeholders/pokesprites/Blastoise.png",
    },
    {
      id: "#blast3",
      apiId: "9",
      ball: "04",
      name: "Michael",
      species: "Blastoise",
      type: ["Water", "Electric"],
      level: 5,
      exp: 12,
      sprite: "/placeholders/pokesprites/Blastoise.png",
    },
  ],
};

export const lineUpArray = Array.from({ length: 6 }, (_, i) => i);
export const elmOptions = [
  "Fire",
  "Water",
  "Grass",
  "Electric",
  "Rock",
  "Psychic",
];
export const genOptions = [
  "I",
  "II",
  "III",
  "IV",
  "V",
  "VI",
  "VII",
  "VIII",
  "IX",
];
export const placeholderPk = [];
